Finale workflow 101 net
temporalio/edu-101-dotnet-code pull request #4
Opened 2024-05-02 18:58 UTC by angelazhou32

2024-05-08 16:57 UTC, MasonEgger requested changes

2024-05-08 16:57 UTC, MasonEgger commented on README.md
> +[these instructions](https://learn.temporal.io/getting_started/dotnet/dev_environment/) to set up your own Temporal Cluster with Docker Compose, which you can use as an exercise environment.
That link doesn't have Docker Compose instructions
```suggestion
[these instructions](https://learn.temporal.io/getting_started/dotnet/dev_environment/) to set up your own Temporal Cluster with the `temporal` CLI, which you can use as an exercise environment.
```

2024-05-08 16:57 UTC, MasonEgger commented on exercises/finale-workflow/README.md
> +Workflow. For example, you might write your Workflow in TypeScript but use
Make it course focused
```suggestion
Workflow. For example, you might write your Workflow in C# but use
```

2024-06-11 13:37 UTC, cretz commented on exercises/finale-workflow/Worker/Program.cs
> +// run the worker
Inconsistent with whether you capitalize your comments

2024-06-11 13:39 UTC, cretz commented on edu-101-net-code.sln
So #5 has solutions in the exercise, #6 has some per project, and this one has one at the root. I think a common one at the root makes sense, but would encourage consistency regardless

2024-06-11 13:41 UTC, cretz commented on exercises/finale-workflow/Client/Program.cs
> +var client = await TemporalClient.ConnectAsync(new ()
Inconsistent with how we are providing the target host to connect compared to #5 and #6

2024-06-11 13:41 UTC, cretz commented on exercises/finale-workflow/Client/Program.cs
> +    new WorkflowOptions
Inconsistent with how we are providing task queue and ID to options compared to #5 and #6

2024-06-11 13:42 UTC, cretz commented on exercises/finale-workflow/Client/Program.cs
> +        Id = "cert-generator-workflow-" + Guid.NewGuid()
```suggestion
        Id = $"cert-generator-workflow-{Guid.NewGuid()}"
```

Other PRs are doing string interpolation

2024-06-11 13:42 UTC, cretz commented on exercises/finale-workflow/Client/Program.cs
> +Console.WriteLine("You can find your certificate of completion here: " + await handle.GetResultAsync());
Inconsistent with whether you do `{0}` style replacers or concatenation

2024-06-11 13:44 UTC, cretz commented on samples/retry-policy/RetryPolicyExample.cs
> +            },
Mentioned in other PR, but would recommend turning on analyzers for all projects and having CI confirm that all code is formatted (e.g. `dotnet format --verify-only`)

2024-06-13 16:03 UTC, angelazhou32 commented on edu-101-net-code.sln
good catch, jwahir has removed the ones in her exercises to keep up with the consistency.

2024-06-17 18:26 UTC, cretz reviewed
Some comments may apply to multiple places but I only made them in the first applicable place. Also comments made on https://github.com/temporalio/edu-101-dotnet-code/pull/5 and https://github.com/temporalio/edu-101-dotnet-code/pull/6 should be assumed to apply here.

Please let me know once all comments are addressed and give me a chance to re-review, thanks!

2024-06-17 18:26 UTC, cretz commented on exercises/finale-workflow/Client/Client.sln
Should not need a solution file for the client since you already have one in the root you can add this project to

2024-06-17 18:26 UTC, cretz commented on edu-101-net-code.sln
Can also put this in `exercises/finale-workflow` if you'd like since it only corresponds to projects under there. Also make sure with `dotnet sln list` that only the projects you want are in there.

2024-06-17 18:26 UTC, cretz commented on edu-101-net-code.sln
Inconsistent with whether your .NET sample projects have a root solution or not

2024-06-17 18:26 UTC, cretz commented on exercises/finale-workflow/Worker/Worker.csproj
> +    <PackageReference Include="Temporalio" Version="1.0.0" />
Inconsistent SDK version number

2024-06-17 18:26 UTC, cretz commented on exercises/finale-workflow/Workflow/CertificateGeneratorWorkflow.cs
> +        return await Workflow.ExecuteActivityAsync<string>("CreatePdf", new object[] { name }, new()
You could make a typed interface, e.g. `IJavaActivities` that has a `string CreatePdf(string name)` call, and then you get type safety. This is usually better than passing strings around.

2024-06-17 18:26 UTC, cretz commented on samples/retry-policy/RetryPolicyExample.cs
> +public class RetryPolicyExample
Where is this class used? Is there anything to confirm it works/compiles? It may not even belong to a project.

2024-07-02 14:13 UTC, cretz approved these changes
Looks good. Would recommend at least a GitHub CI run that confirms it continues to compile (ideally you would have tests too, but I understand if that's asking too much)

2024-07-02 14:15 UTC, cretz commented on exercises.sln
This solution needs all projects from all PRs.

2024-07-08 15:34 UTC, merged