Farewell Workflow Exercise
temporalio/edu-101-dotnet-code pull request #6
Opened 2024-05-07 22:29 UTC by jsundai

## What was changed

## Why?

## Checklist

1. Closes 

2. How was this tested:

3. Any docs updates needed?

2024-05-08 17:20 UTC, MasonEgger requested changes

2024-05-08 17:20 UTC, MasonEgger commented on exercises/farewell-workflow/README.md
> +1. Open the `TranslateActivities.cs` file. This is located in the `practice/Workflow`
Just give them the full path. The following sentence makes them have to construct the path in their head
```suggestion
1. Open the `TranslateActivities.cs` file. This is located in the `exercises/farewell-workflow/practice/Workflow`
```

2024-05-08 17:20 UTC, MasonEgger commented on exercises/farewell-workflow/README.md
> +   subdirectory under the `farewell-workflow` directory in `exercises`.
```suggestion
   subdirectory
```

2024-05-08 17:20 UTC, MasonEgger commented on exercises/farewell-workflow/README.md
> +   2. Rename the new `GetSpanishGreeting` function to `GetSpanishFarewell`.
Add a line here instructing the learner to modify the Activity to call the appropriate URL

```
1. Modify the Activity to call `get-spanish-farewell`
```

2024-05-08 17:20 UTC, MasonEgger commented on exercises/farewell-workflow/README.md
> +2. Look for the TODO message, uncomment the lines below it, and then update this code to execute the Activity function you created.
I would include those instructions in here as well, not just in the source file

2024-05-08 17:20 UTC, MasonEgger commented on exercises/farewell-workflow/README.md
> +Note: If you're using the Gitpod environment to run this exercise, you can skip this step.
I would move this to the top so GitPod learners don't accidentally try to do this then realize they didn't need to. The majority of our learners use GitPod

2024-05-08 17:20 UTC, MasonEgger commented on exercises/farewell-workflow/README.md
> +1. Open a terminal and navigate to the `practice` subdirectory.
Would include the `cd` command as mentioned above.

2024-05-08 23:00 UTC, axfelix commented on exercises/farewell-workflow/practice/Web/Web.http
> +### Get Spanish Greeting
I'm not familiar with `.http` files in dotnet applications but Github's syntax highlighting is suggesting that it doesn't like comments/headers formatted this way... could be wrong and it's fine, just seems worth a head check.

2024-06-11 13:36 UTC, cretz reviewed
Only reviewed `solution` and some comments may apply to multiple places but I only made them in the first applicable place. Also comments made on #5 should be assumed to apply here.

2024-06-11 13:36 UTC, cretz commented on exercises/farewell-workflow/solution/Client/Client.sln
#5 had a solution for the whole exercise, but this is per project. Is the difference intentional?

2024-06-11 13:36 UTC, cretz commented on exercises/farewell-workflow/solution/Workflow/GreetingWorkflow.cs
> +namespace Temporalio.Farewell.Workflow;
#5 used `MyNamespace` but this one uses a more proper namespace. Is the difference intentional? Would like to see #5 get updated with a proper namespace too.

2024-06-11 13:36 UTC, cretz commented on exercises/farewell-workflow/solution/Client/Program.cs
> +string name = (args.Length > 0 && !string.IsNullOrEmpty(args[0])) ? args[0] : "Temporal";  // Default name
```suggestion
var name = args.FirstOrDefault() ?? "Temporal";  // Default name
```

This is a bit clearer (untested),. But why default to `"Temporal"` if you're just going to ask later and default again?

2024-06-11 13:36 UTC, cretz commented on exercises/farewell-workflow/solution/Client/Program.cs
> +var client = await TemporalClient.ConnectAsync(new("localhost:7233") { Namespace = "default" });
Inconsistent with other exercises like #5 on whether you explicitly specify the `"default"` namespace or not

2024-06-17 18:20 UTC, cretz reviewed
Only reviewed `solution` and some comments may apply to multiple places but I only made them in the first applicable place. Also comments made on https://github.com/temporalio/edu-101-dotnet-code/pull/5 should be assumed to apply here.

Please let me know once all comments are addressed and give me a chance to re-review, thanks!

2024-06-17 18:20 UTC, cretz commented on exercises/farewell-workflow/solution/Client/Program.cs
> +Console.WriteLine($"Workflow result: {result}");  // Output Workflow result
Inconsistent with whether you use string interpolation or `{0}` like replacers (#5 used the former, this uses the latter)

2024-06-17 18:20 UTC, cretz commented on exercises/farewell-workflow/solution/Client/Program.cs
> +    name = args.FirstOrDefault() ?? "Temporal";
Why ask for a user's name at all if it's present in args?

2024-06-17 18:20 UTC, cretz commented on exercises/farewell-workflow/solution/Web/Web.csproj
> +    <ProjectReference Include="..\Workflow\Workflow.csproj" />
Are either of these dependencies needed?

2024-06-17 18:20 UTC, cretz commented on exercises/farewell-workflow/solution/Web/Web.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
Arguably OpenAPI is not needed here

2024-06-17 18:20 UTC, cretz commented on exercises/farewell-workflow/solution/Web/Web.csproj
> +    <PackageReference Include="Temporalio" Version="1.1.1" />
Does not look like anything Temporal related is done in this project

2024-06-17 18:20 UTC, cretz commented on exercises/farewell-workflow/solution/Worker/Program.cs
> +            .AddStaticActivities(typeof(TranslateActivities)) // Add Activities
```suggestion
            .AddStaticActivities<TranslateActivities>() // Add Activities
```

This is a bite more idiomatic

2024-06-17 18:20 UTC, cretz commented on exercises/farewell-workflow/solution/Workflow/TranslateActivities.cs
> +    private static readonly HttpClient client = new();
There's an opportunity here to use non-static and DI if you want to inject the HTTP client in the constructor, but don't have to

2024-06-17 18:20 UTC, cretz commented on exercises/farewell-workflow/solution/Workflow/TranslateActivities.cs
> +// Translate Activities
Usually no need for leading comments like this in any of the files (but if you want proper .NET doc you _could_, though that's probably unnecessary too)

2024-06-17 18:20 UTC, cretz commented on exercises/farewell-workflow/solution/Workflow/TranslateActivities.cs
> +        var response = await client.GetAsync($"http://localhost:5125/get-spanish-greeting?name={name}");
You need to escape the `name` for use in a URL parameter

2024-07-02 14:06 UTC, cretz reviewed
Looks good, but I think when you turn on analyzers you'll see more things to fix

2024-07-02 14:06 UTC, cretz commented on exercises/farewell-workflow/solution/Client/Program.cs
> +// Start the Workflow
```suggestion
// Run the Workflow
```

This matches your comments in other PRs

2024-07-02 14:06 UTC, cretz commented on exercises/farewell-workflow/solution/Web/Program.cs
> +        logger.LogInformation($"Returning Spanish greeting: {greeting}");
```suggestion
        logger.LogInformation("Returning Spanish greeting: {Greeting}", greeting);
```

This is the more proper way to use a .NET logger (I think analyzers will warn you here)

2024-07-02 14:06 UTC, cretz commented on exercises/farewell-workflow/solution/Workflow/TranslateActivities.cs
> +    private static readonly HttpClient client = new();
Bump. This actually may be more important now that I have checked and `HttpClient` is `IDisposable`. I suspect when you turn on analyzers, you will get a warning.

2024-07-15 13:22 UTC, merged